### ISSUE TITLE
Ensure subtitles are saved in UTF-8

### ISSUE THREAD

**Issue by tympanix** [tympanix/subsync#3]

**Comment by zship** [comment]
To add to this, I've been getting encoding errors in output .srt's and I think I might see the issue: 

[This line](https://github.com/tympanix/subsync/blob/ca8260f7a28a033374187d9f9efb0969187bb1ea/subsync/media.py#L104) assumes that the input .srt is `'iso-8859-1'`-encoded.  When I get errors it seems to be because the input .srt is UTF-8 already.  A quick sanity check in my shell verifies this sort of situation would lead to the same problem I'm seeing:

```
$ echo 'Bon appétit' | iconv -f iso-8859-1 -t utf-8
Bon appÃ©tit
```

I'm not sure the best way to solve this, but I can think of three:
1. Make utf-8 the default, and point out in the README that input .srt files must be utf-8 encoded.
2. Allow specifying the input encoding with a command line argument, with a sensible default (utf-8?).
3. Detect the input encoding. I've had some success with [enca](https://github.com/nijel/enca), but I'm not sure any automatic detection method can be considered 100% reliable.

P.S. thanks for creating and sharing this!

**Comment by tympanix** [comment]
Glad you found it useful. I can't rally recall my reasoning for choosing anything other than UTF-8. That should be changed. Additionally one may use [chardet](https://pypi.org/project/chardet/) to detect encoding.
